import { Footer } from "@/components/header-footer";
import { Header } from "@/components/header-footer";
import { Metadata } from "next";

export const metadata : Metadata = {
  title: {
    absolute: "",
    default: "Default Title - Next.JS Tutotial - Najeeb",
    template: "Template Title - %s | Najeeb"
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
          <Header ></Header>
          {children}
          <Footer ></Footer>
          </body>
    </html>
  );
}
